### ISSUE TITLE
Alignment is off since Sketch 3.8! Pleaseeeee fix!

### ISSUE THREAD

**Issue by davidvb** [kenmoore/sketch-relabel-button#12]
Hi, Since Sketch 3.8 (now on 3.8.3) the plugin became unusable to me as it no longer correctly repositions as can be seen in the gif below... Is there a fix in the works? 

![giphy](https://cloud.githubusercontent.com/assets/400285/15949130/60669b0a-2ea5-11e6-8bd5-caddd086e96d.gif)

**Comment by kenmoore** [comment]
Hi David, I wonder if you might have an older version of the plugin, can you try removing and reinstalling the latest?  I tried the exact same experiment that you've done and it works as expected on my machine.
