### ISSUE TITLE
Seems to be broken with Sketch 39 release.

### ISSUE THREAD

**Issue by thejmoore** [kenmoore/sketch-relabel-button#14]
Command+J doesn't seem to be pulling up the relabel button dialog. I reckon it has something to do with Sketch's introduction of resizing functions (Pin to corner, Stretch, etc).

**Comment by kenmoore** [comment]
Hi there, I've tried it in Sketch 39 and am having no issues whatsoever.  Could you describe in detail what's happening for you?  Have you tried disabling other plugins and/or reinstalling Relabel Button plugin?

**Comment by ohheyyeahthatsme** [comment]
It stopped working for me with the Sketch update, but after uninstall/reinstall it works again.

**Comment by kenmoore** [comment]
Ok, good to hear.  You're the 2nd report of needing to reinstall... if I hear of more then I'll report back to the Sketch team.
