### ISSUE TITLE
Doesn't work with latest sketch version

### ISSUE THREAD

**Issue by shirah** [kenmoore/sketch-relabel-button#19]
Can you update this plugin to work with the latest sketch version?

**Comment by jcwenzel** [comment]
This is one of my favorite plugins for Sketch. It'd be amazing to have this updated so it works with the current version of Sketch. Thanks!

**Comment by sokos** [comment]
That’s one of the most used plugins by me. Looking forward to an updated version 👍

**Comment by kenmoore** [comment]
@sokos and @jcwenzel  Hello, can you describe in detail what is not working for you? I just confirmed in Sketch 42 that it works as expected in this situation: I created a rectangle background, a text label, and an icon (just an oval as placeholder), grouped the 3 together, then invoked the plugin to relabel it from "Test" to "This is a much wider label".... and as expected the button was widened with the text and icon being placed in proper position.  I'll be happy to update it but need to be able to reproduce the problem.

**Comment by sokos** [comment]
Hi @kenmoore, 
Have to say I've misled you personally. Sorry for that. The plugin still works perfectly but it is deprecated in Sketch 42.
![screen shot 2017-03-05 at 10 36 57](https://cloud.githubusercontent.com/assets/470663/23585172/3da28926-0190-11e7-9218-2431432cc7ac.png)

**Comment by kenmoore** [comment]
Hi @sokos, @jcwenzel and @shirah ... I just posted an update that uses the new plugin bundle format so it should not show up under Legacy anymore. Also, I've added support for symbols which you'll hopefully find useful as well.  Let me know if you encounter any issues.

Ken

**Comment by MDBas** [comment]
Hi Ken,

It doesn't work for symbols for me. Nothing happens when I select 'Relabel button' or hit CMD+J.
Works perfectly for regular groups.

Bas

**Comment by kenmoore** [comment]
@MDBas Hm, maybe I'm making too many assumptions about the symbols. Currently I'm not parsing into groups within the symbols, the text layer needs to be a top-level (ungrouped) layer. Please try a sample symbol with only a text field and a simple shape to the left or right of the text.  If that doesn't shed any light could you send a sample file that you think should work but isn't, and I'll troubleshoot here?  Thanks

**Comment by MDBas** [comment]
Hi Ken,

I tried with only a text layer inside the symbol, but it doesn't work for me.
Here's a sample file.

Thanks,
Bas

[relabel test.sketch.zip](https://github.com/kenmoore/sketch-relabel-button/files/820514/relabel.test.sketch.zip)

**Comment by kenmoore** [comment]
@MDBas 
Hey Bas, thanks for sending the sample file!  It turns out my code wasn't accounting for the case where the text override is blank to start with, and was crashing. I've uploaded a fix, let me know if you can confirm it works.

Ken

**Comment by MDBas** [comment]
Hi Ken,

It does work when the text override isn't blank to start with, but doesn't work when it's blank.

Bas

**Comment by kenmoore** [comment]
Hey Bas, I think this is happening: I forgot to bump the version in the manifest (sorry) so it's not replacing your existing copy of the plugin... please manually remove and reinstall the plugin and I *think* it will work. I'm trying it right now on your test file and it works whether the override is blank or not.

**Comment by MDBas** [comment]
Hi,

I manually removed it, downloaded it and installed it, but still not working when override is blank.

Bas

**Comment by kenmoore** [comment]
Hm, this is odd. I'm on OSX Sierra and Sketch 42, you? What is the exact result you're getting? (does the prompt box appear asking for the new text?)  Could you do Show Package Contents then dig into the Relabel Button.js file to confirm you've got the code changes shown here: https://github.com/kenmoore/sketch-relabel-button/commit/f939470d39a371236f7bd032df2b56330720ff91
Sorry this isn't working more smoothly, I can't imagine what would cause the differences now.

**Comment by MDBas** [comment]
I'm still on El Capitan and Sketch 42.
I do have the code changes in Relabel Button.js.
