### ISSUE TITLE
Apply padding when replacing symbol

### ISSUE THREAD

**Issue by MDBas** [kenmoore/sketch-relabel-button#20]
I have various button symbols: with and without an icon on the left or right.
When I have used the relabel button plugin to change the label, and at some point want to replace a symbol with an icon with a button without an icon, it doesn't apply the padding of the button without an icon.
Is there any way to make this work?

Thanks,
Bas

[replace symbol.mov.zip](https://github.com/kenmoore/sketch-relabel-button/files/823736/replace.symbol.mov.zip)

**Comment by kenmoore** [comment]
Ah interesting.  I don't think this is possible, here's why: Relabel Button examines the present padding, updates the button text, then resizes the button to achieve the original padding.  However, when you change a layer from one symbol type to another, the width of the layer is preserved which means the prior padding measurement (the one you'd like to keep) is discarded. Sorry I can't think of a way to make this easier than creating a new symbol instance of the new type then using Relabel Button on that.

**Comment by WWalmink** [comment]
Related to this: I changed the label of a symbol button and it didn't update the padding. Did I miss something, or is it not possible to automatically change the size of the symbol instance when the label is updated?
