### ISSUE TITLE
Symbol with icon does not update width after label change

### ISSUE THREAD

**Issue by walmink** [kenmoore/sketch-relabel-button#21]
Related to [this issue](https://github.com/kenmoore/sketch-relabel-button/issues/20), but different.

I created two symbols: one without and one with an icon on the left.
When I change the label of the one **without** an icon, the symbol instance resizes properly.
When I change the label of the one **with** an icon, the symbol instance doesn't resize whatsoever.

Am I missing something? As you can see, the symbols are pretty basic and apart from the icon the same.

![image](https://cloud.githubusercontent.com/assets/753479/23941571/87b2edfe-0969-11e7-8e19-1ce1200f9c68.png)

![image](https://cloud.githubusercontent.com/assets/753479/23941665/f97d6e82-0969-11e7-983d-790129a8b136.png)

**Comment by walmink** [comment]
Okay, I discovered the problem...

For others who run into the same problem: don't forget to set the text element to size "auto", not "fixed"! Duh.

**Comment by kenmoore** [comment]
Aha, glad you figured it out! I could probably write some code to force text to auto-size, perhaps at some point I'll do that.

**Comment by walmink** [comment]
interestingly, it takes the padding from the symbol instance, not the symbol. Hence, once you resize the symbol instance, you cannot get back to the "intended" padding anymore (you also can't measure it, because it's inside the symbol).

Maybe the update dialog could ask whether your want the symbol's or the instance's paddings to be used as a reference.

**Comment by kenmoore** [comment]
Ah, that's a good suggestion. I'll keep that in mind for a future update!
