### ISSUE TITLE
Won't apply an override for a symbol in Sketch 43

### ISSUE THREAD

**Issue by tigranpetrossian** [kenmoore/sketch-relabel-button#22]
Great plugin, thanks for finally getting this right, it took a while to find one that's not a headache to use.

As the title says, in Sketch 43 it will change the width properly when new label is applied via CMD+J, but the override for the symbol will stay the same.

**Comment by kenmoore** [comment]
Hey, glad you like the plugin.  Could you check out the Guidelines Sketch file posted alongside the plugin to confirm that your buttons follow the guidelines?  If they are, and are still showing issues, could you attach a sample file where it's not working properly?  Thanks

**Comment by tigranpetrossian** [comment]
@kenmoore Unfortunately it's reproducible on Guidelines file too https://cl.ly/1v2K2w3Z320Z

**Comment by kenmoore** [comment]
Ok, I see Sketch recently deprecated a method without warning, AND their proposed fix for the method is also broken. Unfortunately there's nothing I can do until they provide working sample code, will let you know as soon as it's fixed.

**Comment by kenmoore** [comment]
@tigranpetrossian @einancunlu @shingo-nakanishi You can follow the deprecated API issue here if you want:  http://sketchplugins.com/d/154-applyoverrides-allsymbols-depreciated-in-43/11

**Comment by bumpux** [comment]
Hiya Ken! There's some promising stirrings over on the API issue thread. My withdrawal from Command+J isn't going very well. Maybe you'll have a chance to take a look? For old times' sake :-)

**Comment by vikynandha-zz** [comment]
Hey @kenmoore Thanks for the great plugin. Looks like the Sketch team has suggested a solution (on May 4) and some other developers have confirmed that it's working 🎉 
http://sketchplugins.com/d/154-applyoverrides-allsymbols-depreciated-in-43/22

Would be great if you give it a shot. Thanks in advance :)

**Comment by alexeiboronnikov** [comment]
Fix it please please!

**Comment by daniel-grim89** [comment]
Fix it please please! +1

BTW, I just got an update for Sketch bumping the version to 44 and now the plugin does not work AT ALL.

**Comment by kenmoore** [comment]
@tigranpetrossian @einancunlu @shingo-nakanishi @bumpux @vikynandha @alexeiboronnikov @daniel-grim89 .... got it fixed, works with Sketch 44 (but won't work with 43 anymore).  Sorry for the delay!  Let me know if you encounter any further issues. 

Thanks,
Ken

**Comment by tigranpetrossian** [comment]
Hey Ken,

Thank you so much. Strangely enough, it works perfectly from the examples in **Relabel Button Guidelines.sketch** but nowhere else. Even if I simply duplicate the **Plain Button Symbol** within that file and insert it into the same Artboard. Here's what the log tells me if that's any help:

```
TypeError: sel.addOverrides_forCellAtIndex_ancestorIDs_ is not a function. (In 'sel.addOverrides_forCellAtIndex_ancestorIDs_({ObjectId : "overrideText"}, 0, nil)', 'sel.addOverrides_forCellAtIndex_ancestorIDs_' is undefined)
line: 124
sourceURL: /Users/tigran/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Relabel Button.sketchplugin/Contents/Sketch/Relabel Button.js
column: 51
 «Plugin Output»
```

**Comment by kenmoore** [comment]
@tigranpetrossian Thanks for the feedback -- strange, it's working on my machine following your repro steps.  Have you upgraded to version 44 (the new code won't work with v43)?  I'd typically ask you to attach a sample file, but you're using the same sample file that I am, so I'm not sure how to explain the discrepancy... but maybe attaching a sample file will reveal some clues.

**Comment by tigranpetrossian** [comment]
@kenmoore Yeah, I'm using 44. I'm baffled myself since I seem to be following your instructions.

Here's a video of reproducing on your sample file: https://cl.ly/3M0G0f2A2B1s

And here's a sample file made from scratch that doesn't work for me: https://cl.ly/2j0K3V0v031g

Thanks!

**Comment by bumpux** [comment]
Thanks, Ken. My experience is the same as @tigranpetrossian's. All is well in the sample file. And groups work in any file. But symbols fail outside of the sample file for me, even in a new file with nothing else going on. I tried pasting your symbols in, and creating a symbol from scratch (following new resizing rules). In both cases, ⌘+J on symbols fails (no prompt for input). Detach from symbol, it works.

**Comment by kenmoore** [comment]
Ok, I've reached out to the folks at Bohemian Coding... I'm using a deprecated API and there's absolutely no documentation on the web about it. I'm stuck until I hear back from them, hopefully they'll respond soon.

**Comment by vikynandha-zz** [comment]
Thanks so much @kenmoore. Let's hope they get back soon

**Comment by kenmoore** [comment]
Alrighty, I got the guidance I needed and (I believe!) I've fixed the issue... please give a try and confirm.  Thanks

**Comment by vikynandha-zz** [comment]
Awesome! It's working perfect for both normal groups and symbols @kenmoore 👍

**Comment by kenmoore** [comment]
Super! :)

**Comment by bumpux** [comment]
😀

**Comment by daniel-grim89** [comment]
Hey,

After getting the new update of Sketch (v 45), the plugin stopped working again :( Can you have a look @kenmoore ? Thanks

**Comment by kenmoore** [comment]
@daniel-grim89 I've updated the plugin, please update it and let me know if you encounter any other issues.

**Comment by daniel-grim89** [comment]
Works perfectly! Thanks so much!
