### ISSUE TITLE
Symbol override

### ISSUE THREAD

**Issue by svitelskyi** [kenmoore/sketch-relabel-button#24]
Hello @kenmoore, nice plugin but not working when I create button symbol and try use plugin button resized but text not overridden. Fix please correct work with symbols and text override. Thank You!

Link to example - https://dl.dropboxusercontent.com/s/sev2wreax3ub3sp/2017-05-10%20at%2015.52.png

**Comment by kenmoore** [comment]
Hi @svitelskyi, I just updated the plugin to work with Sketch 44 (they made some data structure changes that broke the plugin).  Give it a try and let me know if you hit any snags.  Thanks.

**Comment by Tharon-C** [comment]
Does this update to Sketch 44 break Sketch 43? I am having the same problem on v43. Works on folder but not on symbol.

![resize-test](https://user-images.githubusercontent.com/7366338/30404607-54783b48-989c-11e7-9663-4670e2120dab.gif)

**Comment by kenmoore** [comment]
@Tharon-C sorry, it's not a goal of mine to support prior releases -- it's tedious enough to support each new release as they deprecate APIs.

**Comment by Tharon-C** [comment]
No worries, just making sure it's not me. Thank you for a super useful tool. Enough to get me to upgrade.
