### ISSUE TITLE
Doesnt work for sketch 45

### ISSUE THREAD

**Issue by imranparvez** [kenmoore/sketch-relabel-button#35]
It wasn't working for sketch 45 so i've rewritten it. 
https://github.com/imranparvez/reLabel
I'm not a developer so the code might not be so great.

**Comment by kenmoore** [comment]
Hi -- please download my latest version and give it a try.  There were some reports of issues with version 45 but I addressed those in my latest update. Let me know if it's still not working for you.

**Comment by vic-georgiev** [comment]
Works fine on 45.2 for me with latest version of the plugin

**Comment by imranparvez** [comment]
Sorry yeah, i downloaded again to check it. It works. My bad.

**Comment by tomdeforest** [comment]
I just downloaded the latest and it isn't working with symbols. It works with normal grouped elements.

**Comment by kenmoore** [comment]
Hi Tom, please download the Guidelines file and see if those symbols work (they work for me with Sketch 45.2).  It may be something about how your symbols are constructed.

https://github.com/kenmoore/sketch-relabel-button/raw/master/Relabel%20Button%20Guidelines.sketch

**Comment by tomdeforest** [comment]
@kenmoore thanks for the follow-up. My button is working now. I followed the instructions for positioning text elements in symbols found in the Guidelines file - this fixed my problem. Thanks!

**Comment by kenmoore** [comment]
Super, glad you got it working!

**Comment by tomdeforest** [comment]
Thanks!
