### ISSUE TITLE
Not working with nested text

### ISSUE THREAD

**Issue by RitRa** [kenmoore/sketch-relabel-button#37]
Hi,
Really cool plugin. Trying to create a design system with nested text so I can change button colour and it doesn't seem to work when the text is converted into a symbol

**Comment by kenmoore** [comment]
Sorry, the plugin doesn't support nested structures and unfortunately I don't have spare time to evolve the plugin further.  Have a look at the guidelines for what is supported: https://github.com/kenmoore/sketch-relabel-button/raw/master/Relabel%20Button%20Guidelines.sketch
