### ISSUE TITLE
Focus never moves to text input

### ISSUE THREAD

**Issue by janedepgen** [kenmoore/sketch-relabel-button#42]
Previously, when you hit the key command for this plugin focus would immediately land on the text input so you could start typing the override - now, focus is trapped between the two buttons which is really inconvenient for a speedy workflow (and is not a11y-friendly for keyboard users)

![feb-07-2019 13-41-03](https://user-images.githubusercontent.com/37704490/52434816-40d02580-2ade-11e9-9665-d0d4ba1dfe35.gif)

**Comment by alexeiboronnikov** [comment]
Same here. This change literally broke my workflow.

**Comment by FabienLaborie** [comment]
Same same, upvote!

**Comment by kenmoore** [comment]
Kudos to Ale Muñoz of the Sketch team for this pull request -- grateful!

**Comment by tbnv** [comment]
Would it be possible to reopen this issue? I'm noticing that the dialog never gets the focus after the keyboard shortcuts. This makes you move from the keyboard to mouse, then back to the keyboard.

**Comment by kenmoore** [comment]
I'm not seeing that issue in Sketch 53.2. Please provide exact steps to reproduce the issue and which version of Sketch you're using. Also, try disabling all other plugins to see if there might be some conflict, I've heard that sometimes happens. Thanks

**Comment by tbnv** [comment]
@kenmoore It was related to this: https://github.com/kenmoore/sketch-relabel-button/issues/32#issuecomment-473353956

🤦‍♂️

**Comment by johnpeele** [comment]
@kenmoore this issue is still present for me. I have disabled all plugins and am running version 53.2.

1. Select button
2. Invoke plugin using keyboard shortcut `cmd+J`
3. Dialog is opened, but no elements are focused - buttons or primary text input
4. Tabbing is also completely disabled - Pressing `TAB` does nothing
5. I then manual focus the text input with my mouse and highlight all text to be replaced

**Comment by kenmoore** [comment]
Hi John,

Do you have version 1.10 of the plugin? If so, I can't explain the issue as
I just tested it and the text does get focused when the dialog pops up for
me. I wish I could help but it sounds like deeper bugs within Sketch, not
an issue with the plugin specifically :^/

Ken

**Comment by vegadesign** [comment]
Hi @kenmoore 
I have the same situation - the input in the popup has no focus by default.
Sketch v.53.2. Button plugin v.1.7

STR:
- Open Skecthapp
- Paste any "button" symbol
- Apply the plugin to a button
(x) the input in the popup has no focus by default
(/) the input in the popup must have the focused state by default

![focus](https://user-images.githubusercontent.com/8604229/55483380-1eb2d980-562f-11e9-9d54-429cbb2d76ce.gif)

**Comment by kenmoore** [comment]
@vegadesign please fetch version 1.10 of the plugin
