### ISSUE TITLE
Doesn't work on sketch 53

### ISSUE THREAD

**Issue by pavelneznanov** [kenmoore/sketch-relabel-button#46]
Relabel Button.js

works with this changes

`60 > initialValue: textLayer,`
`130 > initialValue: textLayer,`
`172 > // sel.setIsSelected(false);`
`173 > // sel.setIsSelected(true);`

**Comment by FabienLaborie** [comment]
Hi @kenmoore , I'm a huge user of this plugin. I always recommend it to my students and put it in their workflows. Any way you can make it work on Sketch 53? Thanks!

**Comment by chiawase** [comment]
I edited the sketch plugin JS files with what @pavelneznanov wrote and added it to `Relabel Button Right Aligned.js` as well.

The following lines need to be changed:
`58 > initialValue: textLayer,`
`125 > initialValue: textLayer,`
`167 > // sel.setIsSelected(false);`
`168 > // sel.setIsSelected(true);`

**Comment by kenmoore** [comment]
Sorry for the delays, folks -- super busy week between family and work.
Grateful for the pull request, @chiawase!

**Comment by FabienLaborie** [comment]
New version is awesome. The focus on the field is back again. Thank you so much, I'm so grateful ! 💪
