### ISSUE TITLE
Sketch 3.4 not working

### ISSUE THREAD

**Issue by microbians** [kenmoore/sketch-relabel-button#5]
For me is not working. It ask for new label but then nothing happens

**Comment by kenmoore** [comment]
Hi Gabriel, I'm not having any issues, though I know there are some problems with 3.4 and multiple documents (sometimes the plugin actually targets a file other than the one that's focused in the foreground).  Can you restart Sketch, open only one document then retry?  Was it working for you prior to the 3.4 upgrade?

**Comment by microbians** [comment]
I will try by uninstalling and re-installing because I see that other plugins are not working, could be something in my configuration and not related your plugin. Sorry Thanks a lot!

**Comment by microbians** [comment]
Was something with my configuration. I reinstall all and now is working fine ;)

**Comment by kenmoore** [comment]
Glad you got it working!
