### ISSUE TITLE
Doesn't like padding numbers in label from Dynamic Button

### ISSUE THREAD

**Issue by megaroeny** [kenmoore/sketch-relabel-button#6]
When I first tried using this plug-in, I had button groups from Dynamic Button plug-in syntax (or whatever). So for example, a label of mine was named _10:20_. Your plug-in did not like this, and was not resizing correctly.

Once I renamed to something else, worked fine! Just thought I'd let you know, since some people might switch from Dynamic Button to this plug-in.

**Comment by kenmoore** [comment]
Thanks for the report, but I've been unable to recreate the issue.  If you can reproduce in the latest Sketch (3.4.4 or later) it'd be super if you could let me know the exact object types and layer names so I can try to reproduce.

**Comment by megaroeny** [comment]
Oh oops. I probably should get the latest version. I'm still on the App Store version. Thanks
